import Head from "next/head";
import Image from "next/image";
import Header from"../components/Header";
import{BiSearchAlt} from "react-icons/Bi";
import{FaMicrophone} from "react-icons/Fa"
export default function Home() {
  return (
    <>
     <Head>
        <title> Google-v1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header*/}
      
      <Header/>

      {/*Body*/}

      <form className="flex flex-col items-center mt-40">
        <Image width="300"
        object-Fit="cover"
         height="100" 
         src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png"/>
         <div className="flex w-full mt-5 mx-auto mx-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-x lg:max-w-2xl">
         <BiSearchAlt className=" w-8 h-8 text-gray-500 mr-3" />
         <input type="text" className="flex-grow focus:outline-none"/>
         <FaMicrophone className="w-8 h-8"/>
         </div>
         <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
         <button className="btn">Google Search</button>
         <button className="btn">I'm Feeling bliss</button>
         </div>
         </form>
      {/*Footer*/}
      </>
  );
}
